### ISSUE TITLE
Enemy hitboxes not triggering constantly

### ISSUE THREAD

**Issue by Jordamnmn** [UQcsse3200/2024-studio-1#119]
## Description
When remaining inside a enemy's hitbox, they only hurt the player single time. It seems like the 'hit' method only occurs when the player moves across the boundary of the hitbox.

## How To Reproduce
Steps to reproduce the behaviour:
1. Get hit by an enemy
2. Don't move

**Comment by vsinh14** [comment]
Is this because of invuln frames? or is this a separate issue from that
