### ISSUE TITLE
Character moves faster diagonally

### ISSUE THREAD

**Issue by dhruvanil55** [UQcsse3200/2024-studio-1#147]
## Description
When moving the player character diagonally, the movement speed is noticeably faster than when moving straight in any single direction (up, down, left, or right). This results in an inconsistent player experience and an unfair speed advantage when moving diagonally.

## How To Reproduce
Steps to reproduce the behaviour:
1. Start the game and control the player character.
2. Use the movement keys to move the character straight in any direction (e.g., right or left).
3. Now, press two movement keys simultaneously (e.g., up-right or down-left) to move the character diagonally.
4. Observe the difference in movement speed between the straight and diagonal directions.

## Expected Behaviour
The player's movement speed should remain consistent regardless of the direction, whether moving diagonally or straight. Moving diagonally should not provide any additional speed advantage.

**Comment by SIN-Willett** [comment]
resolved by #479
