### ISSUE TITLE
Weapon

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#2]
# **Description**
The "Weapons" feature will add an extra layer of depth to the gameplay by allowing players to acquire and use various weapons. This feature will enhance the strategic elements of the game, as players will need to choose the appropriate weapon for different scenarios. Players will be able to find, equip, and upgrade weapons as they progress through the game. Each weapon will have unique attributes and abilities, providing a diverse range of combat experiences.

## SubFeature/component (optional)
Weapon Types: Melee and shotguns
Combat Mechanics: This consider attach ranges, attack speed, hit detection, reloading and environmental interactions for both close-combat (melee) and close- to mid-range firearms (shotgun).
Weapon Drops: Picking up and dropping down weapons which are located randomly on maps.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #27
- [x] #55
- [x] #66
- [x] #65
- [ ] #74

**Completion Deadline:** Aug. 29

# **Extras (optional)**
- [x] Develop inventory management system for weapons

# **Documentation**
- [Weapon Overview](https://github.com/UQcsse3200/2024-studio-1/wiki/Weapons)
- [Testing Plan for Weapon Component](https://github.com/UQcsse3200/2024-studio-1/wiki/Testing-Plan-for-Weapon-Component)
-  [Testing Plan for Weapon Factory](https://github.com/UQcsse3200/2024-studio-1/wiki/Testing-Planning-for-Weapon-Factory)

# **Members**
- Rohan Kumar (rohankumar17)
- Trong Hieu Mai (Magnius001)
- Cao Quoc Thang Hoang (thanghoang7020202)
- Divyansh Agarwal (divyanshddn146)

**Comment by The-AhmadAA** [comment]
Missing description for "Combat mechanics". Also, please don't create any assets from scratch as this will be too time consuming. If existing assets are not readily available or you need help sourcing them, please get in touch with @iishiishii or myself. 
Make sure to update this ticket with links to the task tickets and documentation as they are created. This ticket is approved and you can start creating the associated task tickets.
