### ISSUE TITLE
Item Enhancement and Expansion

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#276]
# **Description**
This feature ticket focuses on adjusting current items, introducing new items, and enhancing item interaction mechanics. The aim is to expand the variety of items available to players, add new functionalities, and refine interactions to enhance the gaming experience. Each task will specifically address elements of gameplay to maintain balance and add strategic depth.

## SubFeatures/components 

Damage Buff Adjustment:
- Fix the damage buff item to properly increases the projectile damage.

Change Player-Item Interaction:
- Implement a key binding that allows players to pick up items when they are nearby, enhancing gameplay fluidity.

Heart:
- Introduce a new 'Heart' item that increases the player's maximum health, adding a layer of strategy to health management.

Bear Trap:
- Develop a 'Bear Trap' item that players can deploy to damage enemies upon contact, adding new defensive strategies.

Target Dummy:
- Add a 'Target Dummy' item that can be placed by players to distract enemies, mimicking player presence.

Red Button:
- Create a 'Red Button' item that, when activated, eliminates all enemies in the room, providing a powerful area effect tool.

Reroll Item:
- Design an item that allows the player to reroll another item on the ground before pickup, adding an element of choice and chance to item interactions.

Teleport Item:
- Develop an item that teleports the player directly to the boss room, enhancing navigation and strategic positioning.

Ring Of Fire:
- Create a ring of fire around the player so when enemies attack they get burned with the surrounding damage.

Tombstone:
- Create an item that spawns a friendly pet to fight with you as you traverse the rooms.

Werewolf Fang (Boss drop):
- Introduce 'Werewolf Fang' that causes bleed damage on enemies. This boss drop from the werewolf adds a persistent damage effect to enhance combat dynamics.

Feather (Boss drop):
- Implement 'Feather' item, providing a 20% critical hit chance. This item, a boss drop from Birdman, augments critical strike capabilities.

Fireball (Boss drop):
- Design and integrate a 'Fireball' item that allows the player to shoot fire projectiles. This item, a boss drop from Kitsune, burns enemies for a short duration.

# **Dependencies**
- [x] #311. Target Dummy implementation is reliant on NPCs being able to attack the correct target based on the priority task.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #307 (Sep. 19)
- [x] #308 (Sep. 22)
- [x] #348 (Sep. 29)
- [x] #312 (Sep. 29)
- [x] #335 (Sep. 29)
- [x] #336 (Sep. 29)
- [x] #337 (Sep. 29)
- [x] #324 (Sep. 29)
- [x] #388 (Oct. 1)
- [x] #389 (Oct. 1)
- [x] #347 (Sep. 29)
- [ ] Design and Implement Fireball Boss Item (Sep. 29)
- [x] Testing (Sep. 30)
- [x] Documentation (Oct. 2)

**Completion Deadline:** Oct. 2

# **Documentation**
TBD

# **Members**
- Keagan Stoessel (@keagan-stoessel)
- Paras Verma (@Parasverma17)
- Jasmine Hong (@Jas2310)
- Divyanshu (@Div1o1)
- Liam Morris (@notinclined)

**Comment by The-AhmadAA** [comment]
Do you have any dependencies? Please make sure to link subtasks to the appropriate task tickets once they are created, and fix the links to documentation as they still point to the example docs.

**Comment by The-AhmadAA** [comment]
Your new items subtask should probably be broken up into separate tasks to more closely match the described items, as they shouldn't all be in one task ticket.

**Comment by keagan-stoessel** [comment]
> Your new items subtask should probably be broken up into separate tasks to more closely match the described items, as they shouldn't all be in one task ticket.

hey, i'm not entirely sure what you mean. I intended them to already be broken up into separate tasks. Such as each new item is gonna be a task ticket in itself. Or do you want me to do this a different way.

**Comment by keagan-stoessel** [comment]
> Your new items subtask should probably be broken up into separate tasks to more closely match the described items, as they shouldn't all be in one task ticket.

Are you talking about the new items development milestone. We intend to create separate task tickets for each new item. I just didn't want to write them all out separately in the milestone section because we have a lot of new items. Or would you like me to do this differently.

**Comment by The-AhmadAA** [comment]
> > Your new items subtask should probably be broken up into separate tasks to more closely match the described items, as they shouldn't all be in one task ticket.
> 
> Are you talking about the new items development milestone. We intend to create separate task tickets for each new item. I just didn't want to write them all out separately in the milestone section because we have a lot of new items. Or would you like me to do this differently.

Ideally these should be listed separately if you intend on writing a task ticket for each, then link to each task ticket from the items on this feature ticket.

**Comment by keagan-stoessel** [comment]
@The-AhmadAA can you review our ticket once more please

**Comment by The-AhmadAA** [comment]
Great work, thanks for fixing that
