### ISSUE TITLE
Picking up gun causes movement/shooting issues

### ISSUE THREAD

**Issue by Jordamnmn** [UQcsse3200/2024-studio-1#291]
## Description
After picking up any weapon (melee or ranged) and moving to a new room, multiple bugs occur.
1. In the next room, you move speed specifically to the left is reduce (only left and no other direction)
2. In the second room, the player (and some other entities) are forcefully moved up so quickly that the player disappears off the top of the screen, soft locking the game (this issue persists until the player picks up another gun, at which point the bug restarts and occurs somewhat randomly)
3. The weapon sprite doesn't load in rooms outside of the one it was picked up in
4. Bullets occasionally de-spawn immediately after firing (I couldnt find a pattern to this but it always occurs in the first room after the gun is collected) (This bug either occurs or doesn't on a room-by-room basis)

## How To Reproduce
Steps to reproduce the behaviour:
1. Pick up a weapon (I usually collected it in the room below the starting room)
2. Exit the room
3. Observe issues

## Notes
I have no idea why the weapon would be related to the player movement

**Comment by thanghoang7020202** [comment]
found it, looks like the character holding an invisible extremely long entity. Will contact the team to solve it.

https://github.com/user-attachments/assets/9b7eae5c-a959-4a6f-baa3-8facbcd4cf4b

**Comment by Jordamnmn** [comment]
wack, nice work

**Comment by Magnius001** [comment]
PR created
