### ISSUE TITLE
Player recollects their own weapon when moving up

### ISSUE THREAD

**Issue by Jordamnmn** [UQcsse3200/2024-studio-1#310]
## Description
When the player moves up while holding a gun, they interact with it's hitbox which initiates the 'pickup item' methods, resulting in the player's ammo refilling constantly.

## How To Reproduce
Steps to reproduce the behaviour:
1. pick up a gun (doesn't appear to occur with the sword/pickaxe, likely because the sprite is higher up)
2. walk up
3. Observe that the player's ammo is refilled (also read the system output for the 'picked up ranged weapon' text)

**Comment by Magnius001** [comment]
This was solved in #305 as the weapon entity created from the player picking the weapon is not a collectible.
