### ISSUE TITLE
Screen assets not found.

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#340]
## Description
Assets for cut scenes have not been added

## How To Reproduce
1. Start the game
2. Choose "Easy"
3. Select "Choose default"

## Expected Behaviour
The game will unable to spawn in a room and crash as the assets needed for the cut scenes are not available

## Screenshots
![Screenshot 2024-09-29 002954](https://github.com/user-attachments/assets/840898ca-b816-4147-bbf8-6f15488abdb6)

## Additional Context
None

## Temporary Fix
None

**Comment by IanP96** [comment]
This was caused by accidental commits to main that introduced unloaded assets. These changed have been reverted and this crash no longer happens.
