### ISSUE TITLE
Game crash on apply setting.

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#352]
## Description
The game would crash when try to apply the setting changes.

## How To Reproduce
Steps to reproduce the behaviour:
1. Go to "Setting"
2. Click on 'Apply"
3. See error

## Expected Behaviour
The game would crash upon clicking `Apply` regardless of changing the settings or not.

## Screenshots
![image](https://github.com/user-attachments/assets/d9cf0fda-41dd-45b0-9c13-37b289a31c67)

## Additional Context
None

## Temporary Fix
None

**Comment by IanP96** [comment]
Are you still getting this? If so, can you share the full stack trace

**Comment by Magnius001** [comment]
Ah, I found the culprit. Window blocked write access to that specific folder due to my specific security setup.

**Comment by IanP96** [comment]
> Ah, I found the culprit. Window blocked write access to that specific folder due to my specific security setup.

Is this just something you had on your computer or could this same thing happen on other Windows computers
