### ISSUE TITLE
Diagonal Shooting

### ISSUE THREAD

**Issue by Jordamnmn** [UQcsse3200/2024-studio-1#403]
# **Description**
The player should be able to shoot diagonally because currently the inability to do so is bad for usability

**Feature:** [Character Clean Up](#410)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Implement feature (Oct. 13)

**Completion Deadline:** Oct. 13

# **Members**
- Jordan Cole [Jordamnmn](https://github.com/Jordamnmn)

**Comment by manya-k** [comment]
closing since it is merged unto main
