### ISSUE TITLE
BossRoom Add Extra animals spawn Test

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#418]
## Description
currently the test for this is the BossHealthDialogue component, however the test is false positive for spawnOtherAnimals method, 

I have commented out this test in my branch

## How To Reproduce
Steps to reproduce the behaviour:
1. comment out the spawnEntityAt code in spawnOtherAnimals
2. run tests 

## Expected Behaviour
test failure 

## Current Behaviour
test passes by checking that the function the function is activated

## Temporary Fix
Comment out test

**Comment by Aryan-S-Gupta** [comment]
Resolved all issues, updated the code and rewrote the test cases, here's my commit from my branch:

https://github.com/UQcsse3200/2024-studio-1/commit/e5929cd88e7a4e89f8ab4c708dd7c980b036f59a

Thankyou for pointing the issue out, fixed now
