### ISSUE TITLE
End Game screen missing Animals and Labels not in the middle

### ISSUE THREAD

**Issue by justarandomnameduh** [UQcsse3200/2024-studio-1#486]
## Description
Some animals are missing in the dead screen, and sometimes the text labels are not in the middle of the screen.

## How To Reproduce
Steps to reproduce the behaviour:
1. Start the game
2. Let the character die due to animals' projectile
4. See abnormal dead screen

## Expected Behaviour
Each animal should have a different ending screen.

## Screenshots
![image](https://github.com/user-attachments/assets/399cbc28-7644-4e17-8d3a-80d4e856f194)

**Comment by manya-k** [comment]
already merged into main and completed
